<?php

namespace MainBundle\Repository;

/**
 * AchatProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AchatProduitRepository extends \Doctrine\ORM\EntityRepository
{
    public function TopDQL()
    {

        $query=$this->getEntityManager()->createQuery("SELECT SUM(p.quantite)AS s, p.produit,p.idProduit ,p.image FROM MainBundle:AchatProduit p  GROUP BY p.idProduit  ORDER BY s DESC");
        $query->setMaxResults(4);
        return $query->getResult();
    }
}
