<?php

namespace MainBundle\Repository;

/**
 * AchatProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AchatProduitRepository extends \Doctrine\ORM\EntityRepository
{
}
