<?php

namespace MainBundle\Repository;

/**
 * BonusTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BonusTokenRepository extends \Doctrine\ORM\EntityRepository
{
}
