<?php

namespace MainBundle\Repository;

/**
 * CategorieOutilsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieOutilsRepository extends \Doctrine\ORM\EntityRepository
{
}
