<?php

namespace MainBundle\Repository;

/**
 * HistoriqueLocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoriqueLocationRepository extends \Doctrine\ORM\EntityRepository
{
}
