<?php

namespace MainBundle\Repository;

/**
 * HorraireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HorraireRepository extends \Doctrine\ORM\EntityRepository
{
    public function horrairesUser($id)
    {
        $query=$this->getEntityManager()->createQuery("SELECT h.id,h.heureDebut,h.heureFin,h.jour FROM MainBundle:Horraire h where h.User=:id");
        $query->setParameter('id',$id);
        return $query->getResult();
    }
    public function supprimerJour($idUser,$idJour)
    {
        $query=$this->getEntityManager()->createQuery("DELETE FROM MainBundle:Horraire h where h.User=:idUser and h.jour=:idJour");
        $query->setParameter('idUser',$idUser);
        $query->setParameter('idJour',$idJour);
        $query->execute();
        return true;
    }
}
