<?php

namespace MainBundle\Repository;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findNotification($idOutil,$idUser)
    {
        $query=$this->getEntityManager()->createQuery("SELECT n FROM MainBundle:Notification n 
                                                            where n.description like :idOutil and n.description like :idUser");
        $query->setParameter('idOutil','%'.$idOutil->getNom().'%');
        $query->setParameter('idUser','%'.$idUser->getFirstname().'%');
        return $query->getResult();
    }
    public function triNotificationASC()
    {
        $query=$this->getEntityManager()->createQuery("SELECT n FROM MainBundle:Notification n ORDER BY n.notification_date ");
        return $query->getResult();
    }
}
