<?php

namespace MainBundle\Repository;

/**
 * OutilsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OutilsRepository extends \Doctrine\ORM\EntityRepository
{
}
