<?php

namespace MainBundle\Repository;

/**
 * OutilsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OutilsRepository extends \Doctrine\ORM\EntityRepository
{
    public function triNomASC()
    {
        $query=$this->getEntityManager()->createQuery("SELECT o FROM MainBundle:Outils o ORDER BY o.nom ");
        return $query->getResult();
    }
    public function triPrixASC()
    {
        $query=$this->getEntityManager()->createQuery("SELECT o FROM MainBundle:Outils o ORDER BY o.prix ");
        return $query->getResult();
    }
    public function triNomDSC()
    {
        $query=$this->getEntityManager()->createQuery("SELECT o FROM MainBundle:Outils o ORDER BY o.nom DESC");
        return $query->getResult();
    }
    public function triPrixDSC()
    {
        $query=$this->getEntityManager()->createQuery("SELECT o FROM MainBundle:Outils o ORDER BY o.prix DESC");
        return $query->getResult();
    }
}
