<?php

namespace MainBundle\Repository;

/**
 * PaiementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaiementRepository extends \Doctrine\ORM\EntityRepository
{
    public function paiementsUser($id)
    {
        $query=$this->getEntityManager()->createQuery("SELECT p FROM MainBundle:Paiement p where p.IdUser=:id ORDER BY p.datePaiement DESC");
        $query->setParameter('id',$id);
        return $query->getResult();
    }
    public function statAnnee()
    {
        $query=$this->getEntityManager()->createQuery("
                  SELECT month(p.datePaiement) AS M,sum(p.montant) MON from MainBundle:Paiement p 
                  where datediff(now(),p.datePaiement)/365<=1 group BY M ORDER BY p.datePaiement");
        return $query->execute();
    }
    public function venteCetteAnnee()
    {
        $query=$this->getEntityManager()->createQuery("
                  SELECT sum(p.montant) MON from MainBundle:Paiement p 
                  where year(p.datePaiement)=year(now())");
        return $query->execute();
    }
    public function venteTotal()
    {
        $query=$this->getEntityManager()->createQuery("
                  SELECT sum(p.montant) MON from MainBundle:Paiement p ");
        return $query->execute();
    }
}
