<?php

namespace MainBundle\Repository;

/**
 * PaiementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaiementRepository extends \Doctrine\ORM\EntityRepository
{
    public function paiementsUser($id)
    {
        $query=$this->getEntityManager()->createQuery("SELECT p FROM MainBundle:Paiement p where p.IdUser=:id");
        $query->setParameter('id',$id);
        return $query->getResult();
    }
}
