<?php

namespace MainBundle\Repository;

/**
 * PaimentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaimentRepository extends \Doctrine\ORM\EntityRepository
{
}
