<?php

namespace MainBundle\Repository;

/**
 * ProduitLikeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitLikeRepository extends \Doctrine\ORM\EntityRepository
{
    public function counDQL($id)
    {

        $query=$this->getEntityManager()->createQuery("SELECT COUNT(p) FROM MainBundle:ProduitLike p where p.produit = :id ");
        $query->setParameter('id',$id);
        return $query->getResult();
    }
    public function TotalDQL()
    {

        $query=$this->getEntityManager()->createQuery("SELECT COUNT(p) FROM MainBundle:ProduitLike p ");
        return $query->getResult();
    }
    public function SupLikesDQL($id)
    {

        $query=$this->getEntityManager()->createQuery("DELETE FROM MainBundle:ProduitLike p where p.produit = :id ");
        $query->setParameter('id',$id);
        return $query->getResult();
    }


}
