<?php

namespace MainBundle\Repository;

/**
 * ProduitLikeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitLikeRepository extends \Doctrine\ORM\EntityRepository
{
}
