<?php

namespace MainBundle\Repository;

/**
 * QuizUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuizUserRepository extends \Doctrine\ORM\EntityRepository
{
}
