<?php

namespace MainBundle\Repository;

/**
 * RealisationServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RealisationServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
