<?php

namespace MainBundle\Repository;

/**
 * RealisationServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RealisationServiceRepository extends \Doctrine\ORM\EntityRepository
{
    public function findServiceRealise($idUser)
    {
        $query=$this->getEntityManager()
            ->createQuery("SELECT s FROM MainBundle:RealisationService s where s.UserDemandeur=:id")
            ->setParameter('id',$idUser);
        return $query->getResult();
    }

    public function findUsersReclame($idUser)
    {
        $query=$this->getEntityManager()
            ->createQuery("SELECT u from MainBundle:User u JOIN MainBundle:RealisationService s where s.UserOffreur = u.id  and s.UserDemandeur=:id ")
            ->setParameter('id',$idUser);
        return $query->getResult();
    }

    public function findServicesRealise($idUserOffreur,$idUserDemandeur)
    {
        $query=$this->getEntityManager()
            ->createQuery("SELECT ser from MainBundle:Service ser JOIN MainBundle:RealisationService s where ser.id = s.service  and s.UserOffreur=:id and
             s.UserDemandeur=:id1")
            ->setParameter('id1',$idUserDemandeur)
            ->setParameter('id',$idUserOffreur);
        return $query->getResult();
    }
    public function findDateRealisation($idUserOffreur,$idUserDemandeur,$idService)
    {
        $query=$this->getEntityManager()
            ->createQuery("SELECT s.DateRealisation FROM MainBundle:RealisationService s where s.UserOffreur=:id and s.UserDemandeur=:id1
             and s.service=:id2")
            ->setParameter('id1',$idUserDemandeur)
            ->setParameter('id2',$idService)
            ->setParameter('id',$idUserOffreur);
        return $query->getResult();
    }

}
