<?php

namespace MainBundle\Repository;

/**
 * ReposRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReposRepository extends \Doctrine\ORM\EntityRepository
{
    public function reposUser($id)
    {
        $query=$this->getEntityManager()->createQuery("SELECT r.id FROM MainBundle:Repos r where r.User=:id");
        $query->setParameter('id',$id);
        return $query->getResult();
    }
    public function supprimerRepos($idUser,$idJour)
    {
        $query=$this->getEntityManager()->createQuery("DELETE FROM MainBundle:Repos r where r.User=:idUser and r.id=:idJour");
        $query->setParameter('idUser',$idUser);
        $query->setParameter('idJour',$idJour);
        $query->execute();
        return true;
    }
}
