<?php

namespace MainBundle\Repository;

/**
 * ServiceUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceUserRepository extends \Doctrine\ORM\EntityRepository
{
}
