<?php

namespace MainBundle\Repository;

/**
 * ServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceRepository extends \Doctrine\ORM\EntityRepository
{
    public function groupByCat()
    {
        $query=$this->getEntityManager()->createQuery("SELECT m from MainBundle:Service m group by m.CategorieService");
        return $query->getResult();

    }
}
