<?php

namespace MainBundle\Repository;

/**
 * UserOutilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserOutilRepository extends \Doctrine\ORM\EntityRepository
{
    public function premierOutilDQL($idOutil)
    {
        $query=$this->getEntityManager()->createQuery("SELECT uo FROM MainBundle:UserOutil uo 
                                                            where uo.idOutil=:idOutil
                                                            ORDER BY uo.dateRetour ");
        $query->setParameter('idOutil',$idOutil);
        $query->setMaxResults(1);
        return $query->getResult();
    }
    public function mesOutilsDQL($iduser)
    {
        $query=$this->getEntityManager()->createQuery("SELECT uo FROM MainBundle:UserOutil uo 
                                                            where uo.idUser=:iduser");
        $query->setParameter('iduser',$iduser);
        return $query->getResult();
    }
    public function location($idOutil,$idUser)
    {
        $query=$this->getEntityManager()->createQuery("SELECT uo FROM MainBundle:UserOutil uo 
                                                            where uo.idOutil=:idOutil and uo.idUser=:idUser");
        $query->setParameter('idOutil',$idOutil);
        $query->setParameter('idUser',$idUser);
        return $query->getResult();
    }
}
