<?php

namespace MainBundle\Repository;

use MainBundle\Entity\Paiement;
use MainBundle\Entity\Transaction;
use MainBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function listLangueUser($id)
    {
        $query=$this->getEntityManager()->createQuery("
        SELECT l.libelle,l.id 
        FROM MainBundle:Langue l,MainBundle:UserLangue lu
        where lu.idUser=:id AND lu.idLangue=l.id");
        $query->setParameter('id',$id);
        return $query->getResult();
    }
    public function getSolde($id)
    {
        $query=$this->getEntityManager()->createQuery("
        SELECT u.solde
        FROM MainBundle:User u
        where u.id=:id");
        $query->setParameter('id',$id);
        return $query->getResult();
    }
    public function listUsers($nom,$ville)
    {
        $str="SELECT u
            FROM MainBundle:User u
            where u.roles='a:0:{}' AND (upper(u.firstname) LIKE :name OR upper(u.lastname) LIKE :name)";
        if (strlen($ville)!=0)
            $str=$str."AND upper(u.city) LIKE '%".strtoupper($ville)."%'";

        $query=$this->getEntityManager()->createQuery($str);
        $query->setParameter('name',"%".strtoupper($nom)."%");
        return $query->getResult();
    }
    public function visitorsToday()
    {
        $query=$this->getEntityManager()->createQuery("
                  SELECT sum(u.id) VIS from MainBundle:User u 
                  where date(u.lastLogin)=date(now())");
        return $query->execute();
    }
    public function acheterProduit($idA,$idV,$montant)
    {
        $connect=$this->getEntityManager();
        $userA=$connect->getRepository(User::class)->find($idA);
        $userV=$connect->getRepository(User::class)->find($idV);
        if ($userA->getSolde()<$montant)
        {
            return false;
        }
        else
        {
            $transaction=new Transaction();
            $transaction->setMonatantScoin($montant);
            $transaction->setType("Achat");
            $transaction->setUserP($userA);
            $transaction->setUserR($userV);
            $transaction->setDate(new \DateTime());
            $connect->persist($transaction);
            $connect->flush();

            $userA->setSolde($userA->getSolde()-$montant);
            $connect->flush();

            $userV->setSolde($userV->getSolde()+$montant);
            $connect->flush();
            return true;
        }
    }
    public function payerService($idA,$idV,$montant)
    {
        $connect=$this->getEntityManager();
        $userA=$connect->getRepository(User::class)->find($idA);
        $userV=$connect->getRepository(User::class)->find($idV);
        if ($userA->getSolde()<$montant)
        {
            return false;
        }
        else
        {
            $transaction=new Transaction();
            $transaction->setMonatantScoin($montant);
            $transaction->setType("Service");
            $transaction->setUserP($userA);
            $transaction->setUserR($userV);
            $transaction->setDate(new \DateTime());
            $connect->persist($transaction);
            $connect->flush();

            $userA->setSolde($userA->getSolde()-$montant);
            $connect->flush();

            $userV->setSolde($userV->getSolde()+$montant);
            $connect->flush();
            return true;
        }
    }
    public function louerOutil($idA,$montant)
    {
        $connect=$this->getEntityManager();
        $userA=$connect->getRepository(User::class)->find($idA);
        if ($userA->getSolde()<$montant)
        {
            return false;
        }
        else
        {
            $transaction=new Transaction();
            $transaction->setMonatantScoin($montant);
            $transaction->setType("Location");
            $transaction->setUserP($userA);
            $transaction->setDate(new \DateTime());
            $connect->persist($transaction);
            $connect->flush();

            $userA->setSolde($userA->getSolde()-$montant);
            $connect->flush();
            return true;
        }
    }
    public function getPassword($email)
    {
        $query=$this->getEntityManager()->createQuery("
        SELECT u
        FROM MainBundle:User u
        where u.email=:email OR u.username=:email");
        $query->setParameter('email',$email);
        return $query->getResult();
    }
    public function getEmail($email)
    {
        $query=$this->getEntityManager()->createQuery("
        SELECT u
        FROM MainBundle:User u
        where u.email=:email");
        $query->setParameter('email',$email);
        return $query->getResult();
    }
    public function getUsername($username)
    {
        $query=$this->getEntityManager()->createQuery("
        SELECT u
        FROM MainBundle:User u
        where u.username=:username");
        $query->setParameter('username',$username);
        return $query->getResult();
    }
}
