<?php

namespace MainBundle\Repository;

/**
 * UserOutilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserOutilRepository extends \Doctrine\ORM\EntityRepository
{
}
