<?php

namespace MainBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function listLangueUser($id)
    {
        $query=$this->getEntityManager()->createQuery("
        SELECT l.libelle,l.id 
        FROM MainBundle:Langue l,MainBundle:UserLangue lu
        where lu.idUser=:id AND lu.idLangue=l.id");
        $query->setParameter('id',$id);
        return $query->getResult();
    }
    public function getSolde($id)
    {
        $query=$this->getEntityManager()->createQuery("
        SELECT u.solde
        FROM MainBundle:User u
        where u.id=:id");
        $query->setParameter('id',$id);
        return $query->getResult();
    }
    public function listUsers($nom,$languesR,$zipcode,$ville)
    {
        $str="SELECT u
            FROM MainBundle:User u
            where u.roles='a:0:{}' AND (upper(u.firstname) LIKE :name OR upper(u.lastname) LIKE :name)";
        if (strlen($zipcode)!=0)
            $str=$str."AND u.zipCode LIKE '%".$zipcode."%'";
        if (strlen($ville)!=0)
            $str=$str."AND upper(u.city) LIKE '%".strtoupper($ville)."%'";

        $query=$this->getEntityManager()->createQuery($str);
        $query->setParameter('name',"%".strtoupper($nom)."%");
        return $query->getResult();
    }
    public function visitorsToday()
    {
        $query=$this->getEntityManager()->createQuery("
                  SELECT sum(u.id) VIS from MainBundle:User u 
                  where date(u.lastLogin)=date(now())");
        return $query->execute();
    }
}
