<?php

namespace MainBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function listLangueUser($id)
    {
        $query=$this->getEntityManager()->createQuery("
        SELECT l.libelle,l.id 
        FROM MainBundle:Langue l,MainBundle:UserLangue lu
        where lu.idUser=:id AND lu.idLangue=l.id");
        $query->setParameter('id',$id);
        return $query->getResult();
    }
}
