main_homepage:
    path:     /
    defaults: { _controller: MainBundle:Default:index }

################# ROUTING DE MUSTAPHA PLEASE DON'T TOUCH #####################

main_reclamation_Ajout:
    path:     /Reclamer
    defaults: { _controller: MainBundle:Reclamation:AjouterReclamation }
main_affiche_Detail_Reclamation:
        path:     /Reclamer/Detail/{reclamation}
        defaults: { _controller: MainBundle:Reclamation:AfficherDetail }
main_modifier_reclamation:
    path:     /Reclamer/Modifier/{rec}
    defaults: { _controller: MainBundle:Reclamation:ModifierReclamation }
main_mes_reclamation:
    path:     /listreclamations
    defaults: { _controller: MainBundle:Reclamation:MesReclamation }
main_supprimer_reclamation:
    path:     /Reclamer/Supprimer/{rec}
    defaults: { _controller: MainBundle:Reclamation:SupprimerReclamation }
main_liste_reclamation_admin:
    path:     /Backoffice/ListeReclamation
    defaults: { _controller: MainBundle:Reclamation:ListeReclamationAdmin }
main_change_status_reclamation:
    path:     /Backoffice/detaillerec/{rec}
    defaults: { _controller: MainBundle:Reclamation:detaillerecadmin }
main_traite_reclamation_admin:
    path:     /Backoffice/traite/{rec}
    defaults: { _controller: MainBundle:Reclamation:traiteadmin }
main_supprimer_reclamation_admin:
    path:     /Backoffice/supp/{rec}
    defaults: { _controller: MainBundle:Reclamation:supprimeradmin }

############################ END ROUNTING DE MUSTAPHA ##########################
###########################ali#######################
main_ajouterCategori_Produit:
    path:    /ajouterCategorieProduits
    defaults: { _controller: MainBundle:CategorieProduit:ajouter }
main_listCategorie_Produit:
    path:    /listCategorieProduits
    defaults: { _controller: MainBundle:CategorieProduit:lister }
main_supprimerCategorie_Produit:
    path:    /listCategorieProduits
    defaults: { _controller: MainBundle:CategorieProduit:supprimer }
main_modifierCategorie_Produit:
    path:    modfierCategorieProduits/{cat}
    defaults: { _controller: MainBundle:CategorieProduit:modifier }
main_ajouter_Produit:
    path:    /ajoutProduits
    defaults: { _controller: MainBundle:Produit:ajouter }
main_modifier_Produit:
    path:    modifierProduits/{prod}
    defaults: { _controller: MainBundle:Produit:modifier }
main_supprimer_Produit:
    path:    supprimerProduits/{prod}
    defaults: { _controller: MainBundle:Produit:Supprimer }
main_mes_produit:
    path:     /listproduit
    defaults: { _controller: MainBundle:Produit:MesProduit }
    #######################end routing ali #########################
    ################# ROUTING DE Sl-Wassim PLEASE DON'T TOUCH #####################
main_ajouterCategorieOutil:
    path: /ajouterCategorieOutil
    defaults: { _controller: MainBundle:categorieOutil:ajouter }
main_ajouterOutil:
    path: /ajouterOutil
    defaults: { _controller: MainBundle:Outil:ajouter }
############################ END ROUNTING DE Sl-Wassim ##########################